### PR TITLE
Update sample sdk

### LINKED ISSUE #115: Update library and sample app to target SDK 28
> This is a reminder that starting November 1, 2019, updates to apps and games on Google Play will be required to target Android 9 (API level 28) or higher. After this date, the Play Console will prevent you from submitting new APKs with a targetSdkVersion less than 28.

Update the sample app and check that it runs OK.

I will handle uploading the updated app to the Play Store.

### PR DESCRIPTION
**Pull request by rstockbridge**
This closes #115.

Update target SDK and version number of sample app.

### CODE REVIEW

**Comment by rstockbridge** [comment]
Here's the error from Travis CI:

Screen Shot 2019-10-11 at 9 45 55 PM

**Comment by stkent** [comment]
#115 requests a targetSdk of 29, but that might not be possible without first closing #116 since I believe 28.X are the last versions of the old support library artifacts.

I will merge this once CI is fixed, then reopen #115 and note that it is dependent on #116.

To fix CI: my guess is you'll need to edit the `.travis.yml` file in this repo and bump the relevant version numbers up.

**Comment by rstockbridge** [comment]
My mistake, I didn't spot the 29 in the issue title. Will follow the
recommended steps tomorrow!

**Comment by stkent** [comment]
Closing now that #115 has been edited to narrow the scope.

**Pull request closed without merging**
