### PR TITLE
add notes to readme regarding using with sdk versions < 16

### PR DESCRIPTION
**Pull request by bzabor**
I installed bugshaker on an app with minSdkVersion=15 and ran into a small error. I updated the README with notes on what I did.

### CODE REVIEW

**Comment by stkent** [comment]
@bzabor just saw this; does JJs support back to 15? I don't think I use anything in the library that would prevent me from lowering the minSdk...

**Comment by bzabor** [comment]
@stkent JJs minSdk is 16:

```
    defaultConfig {
        applicationId "com.jimmyjohns"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 7
        versionName "3.2.1"
    }
```

**Comment by stkent** [comment]
Ah, so it was a different app? What I'll probably do instead of merging this PR is open a new issue to drop the minSdk of the library. If that proves troublesome for any reason (I can't imagine that it would), I'll revisit this PR and merge in the suggested README section. Sound good?

**Comment by bzabor** [comment]
yup!

**Comment by stkent** [comment]
Awesome, I'll link the issue back to this PR in a sec.

**Comment by stkent** [comment]
Generated issue #90 based on this PR.

**Pull request closed without merging**
